name: Lint

on:
  push:
    branches-ignore:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate terraform configuration
    strategy:
      fail-fast: false
      matrix:
        path: ["cg_space", "clamav", "database", "domain", "redis", "s3", "egress_proxy"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform validate ${{ matrix.path }}
        uses: dflook/terraform-validate@v1
        with:
          path: ${{ matrix.path }}

  fmt-check:
    runs-on: ubuntu-latest
    name: Check formatting of terraform files
    strategy:
      fail-fast: false
      matrix:
        path: ["cg_space", "clamav", "database", "domain", "redis", "s3", "egress_proxy"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform fmt ${{ matrix.path }}
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ${{ matrix.path }}
