name: Terraform Test

on:
  pull_request:
    branches:
      - main

# Security: restrict GITHUB_TOKEN to least privilege.
# See: https://www.upwind.io/feed/hackerbot-claw-github-actions-pull-request-rce
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration test
    concurrency:
      group: terraform-test-${{ matrix.module }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        module: ["s3", "database", "redis", "cg_space", "domain", "clamav", "spiffworkflow"]
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: terraform test ${{ matrix.module }}
        uses: dflook/terraform-test@v1
        env:
          CF_API_URL: "https://api.fr-stage.cloud.gov"
          CF_USER: ${{ secrets.CF_USER }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        with:
          path: ${{ matrix.module }}

  test-with-zip:
    runs-on: ubuntu-latest
    name: Integration test with zip
    concurrency:
      group: terraform-test-${{ matrix.module }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        module: ["egress_proxy", "drupal", "application", "logshipper"]
    env:
      TERRAFORM_PRE_RUN: |
        apt-get update
        apt-get install -y zip

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: terraform test ${{ matrix.module }}
        uses: dflook/terraform-test@v1
        env:
          CF_API_URL: "https://api.fr-stage.cloud.gov"
          CF_USER: ${{ secrets.CF_USER }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        with:
          path: ${{ matrix.module }}
